/**
 * actiontypes.js
 * Created by shanecalhoun on 12/24/17
 */

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_MAIN_SUCCESS = 'GET_MAIN_SUCCESS';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLIENT_VALIDATION_ERROR = 'CLIENT_VALIDATION_ERROR';
export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';
export const SHOW_LOADING_INDICATOR = 'SHOW_LOADING_INDICATOR';

